// export const  USER_API_ENDPOINT = "http://localhost:3000/api/v1/users"
// export const  JOB_API_ENDPOINT = "http://localhost:3000/api/v1/job"
// export const  APPLICATION_API_ENDPOINT = "http://localhost:3000/api/v1/application"
// export const  COMPANY_API_ENDPOINT = "http://localhost:3000/api/v1/company"
export const  USER_API_ENDPOINT = "https://job-portal-app-backend-1-ghf0.onrender.com/api/v1/users"
export const  JOB_API_ENDPOINT = "https://job-portal-app-backend-1-ghf0.onrender.com/api/v1/job"
export const  APPLICATION_API_ENDPOINT = "https://job-portal-app-backend-1-ghf0.onrender.com/api/v1/application"
export const  COMPANY_API_ENDPOINT = "https://job-portal-app-backend-1-ghf0.onrender.com/api/v1/company"